### ISSUE TITLE
Want to use elapsed event.

### ISSUE THREAD

**Issue by sasagar** [coskuncayemre/vue3-flip-countdown#2]
I would like to hide the flip timer after elapsed, and change it to the text.

I think Vue2 version (I mean the original flip countdown) has the event.
So, I want it too for vue3-flip-countdown.

**Comment by coskuncayemre** [comment]
Hi @sasagar, timeElapsed emit is done. I'll release new version asap. :)

**Comment by coskuncayemre** [comment]
I published a new version just ago.
